# Merging Data

In [3]:
import pandas as pd
import matplotlib.pyplot as plt

chip = pd.read_csv("fast food.csv", sep=",")


zipList = []
for i in range(837):#test for the zip code 15203 since it comes up 3 times in 0-15
    x = chip.iloc[i, 5]
    zipList.append(x)

d = dict()
for c in zipList:
    if c not in d:
        d[c] = 1
    else:
        d[c] = d[c] + 1


column_names=["Zip Code","Fast Food Resterants"]

#df = pd.DataFrame(d, index=['i',], columns=column_names)
df_FastFood = pd.DataFrame(list(d.items()), columns=column_names)
df_FastFood = df_FastFood.sort_values('Fast Food Resterants', ascending=False)

In [5]:
import re

def getzc(incidentLocation):#this method is used to take the information under the Incident Location column and get the zip code
    zc = r'\b\d{5}\b' #matches 5 digits at the end of a string
    y = re.search(zc, incidentLocation)
    
    if y:#zip code is found
        return y.group(0)
    else:#no zip code is found
        return None
    
chip = pd.read_csv("Police Incident Blotter data.csv", sep=",")



zipList = []
for i in range(312145):
    x = chip.iloc[i, 4]
    xzc = getzc(x)
    #print(xzc) #will print either a 5 digit zip code or "None"
    zipList.append(xzc)
    
d = dict()
for c in zipList:
    if c not in d:
        d[c] = 1
    else:
        d[c] = d[c] + 1
        
print("this is the number of crimes per zip code from January 1st, 2016, to Febuary 18th, 2023")
print(d)
print("there are ", len(d), " different zip codes in this data set")

        

column_names=["Zip Code","Crime Rates"]

#df = pd.DataFrame(d, index=['i',], columns=column_names)
df_CrimeRates = pd.DataFrame(list(d.items()), columns=column_names)
df_CrimeRates= df_CrimeRates.sort_values('Crime Rates', ascending=False)

this is the number of crimes per zip code from January 1st, 2016, to Febuary 18th, 2023
{'15212': 34146, '15201': 8705, '15214': 9465, '15222': 17142, '15203': 19300, '15220': 5473, '15221': 8983, '15210': 25467, '15213': 13481, None: 33299, '15224': 7786, '15216': 6126, '15219': 21958, '15211': 7596, '15205': 3970, '15206': 24106, '15232': 5619, '15226': 8225, '15204': 7860, '15217': 11487, '15122': 31, '15233': 5520, '15016': 1, '15208': 11349, '15207': 8592, '15215': 578, '15106': 93, '15238': 778, '15227': 2136, '15234': 741, '60603': 1, '16206': 1, '15120': 151, '15136': 82, '15218': 627, '15140': 6, '15235': 161, '15147': 100, '15065': 5, '17025': 1, '15223': 35, '15642': 4, '15132': 59, '15059': 1, '15236': 34, '15088': 1, '32656': 1, '15230': 3, '16635': 1, '15237': 51, '15104': 38, '15110': 9, '63105': 1, '15137': 13, '18951': 1, '15045': 6, '15202': 55, '15229': 12, '15426': 1, '15112': 12, '15317': 4, '15148': 5, '11590': 1, '15146': 56, '15301': 17, '15470': 1, '67202': 1, '15068': 25, '15145': 15, '15108': 19, '15260': 16, '15063': 2, '11375': 1, '15054': 1, '15906': 3, '15001': 6, '15282': 11, '15401': 4, '15123': 2, '73084': 1, '15748': 2, '21211': 1, '15129': 7, '15656': 1, '16101': 1, '15066': 2, '12508': 1, '28217': 1, '14224': 1, '26508': 2, '10010': 1, '15209': 24, '15225': 8, '15131': 5, '18466': 1, '15102': 6, '16502': 1, '15062': 4, '18219': 1, '55104': 1, '15261': 5, '15241': 8, '15124': 3, '20815': 1, '15613': 2, '15101': 7, '15050': 1, '15323': 2, '25401': 1, '60639': 1, '14625': 1, '15228': 8, '44109': 1, '19320': 1, '37211': 1, '15231': 11, '46901': 1, '02439': 1, '15090': 4, '15239': 8, '16066': 4, '15252': 1, '15010': 4, '48084': 1, '16001': 7, '16146': 2, '15012': 2, '10001': 1, '29170': 1, '15028': 1, '44634': 1, '25217': 1, '26554': 1, '17532': 1, '15160': 1, '20018': 1, '22207': 1, '16021': 1, '15644': 3, '32809': 1, '31907': 1, '15417': 1, '15200': 1, '15116': 12, '15071': 2, '23224': 1, '15144': 3, '15936': 1, '15074': 3, '15248': 1, '98201': 1, '15328': 2, '15609': 1, '16323': 1, '26059': 1, '15650': 2, '15275': 7, '15143': 7, '16205': 1, '15005': 1, '16063': 4, '15003': 7, '16216': 1, '30253': 1, '15367': 2, '15017': 7, '18644': 1, '15142': 1, '15527': 1, '15061': 2, '26003': 2, '15296': 1, '17751': 1, '15666': 2, '15240': 3, '02155': 1, '15084': 4, '16743': 1, '16002': 1, '43952': 1, '26501': 1, '18252': 1, '14148': 1, '15243': 6, '32301': 1, '18301': 1, '93291': 1, '15425': 2, '80301': 1, '34102': 1, '15459': 1, '17512': 1, '37042': 1, '44074': 1, '15126': 3, '15057': 2, '15024': 1, '15334': 1, '15121': 1, '19801': 1, '16046': 4, '16201': 1, '89014': 1, '15601': 6, '14207': 1, '30303': 1, '27597': 1, '21842': 2, '15683': 1, '13212': 1, '43953': 1, '89109': 1, '14736': 1, '15904': 2, '15272': 3, '15139': 1, '44321': 1, '30224': 1, '26062': 1, '20001': 1, '51212': 1, '48501': 1, '15242': 1, '16137': 1, '19107': 1, '22312': 1, '16148': 2, '15004': 1, '15801': 2, '11955': 1, '15313': 1, '81244': 2, '16057': 2, '43235': 1, '15033': 1, '15009': 1, '15626': 1, '15668': 1, '44460': 1, '15128': 1, '19405': 1, '15690': 1, '15044': 3, '15025': 6, '94572': 1, '15943': 1, '33461': 1, '22835': 1, '16055': 1, '16064': 1, '16120': 1, '15078': 1, '15658': 1, '02492': 1, '15285': 1, '97214': 1, '21075': 1, '11208': 1, '33624': 1, '15522': 2, '44906': 1, '17103': 1, '25207': 1, '70601': 1, '06484': 1, '15342': 1, '70006': 1, '15632': 2, '45011': 1, '15133': 2, '19596': 1, '16503': 3, '25303': 1, '15475': 1, '44305': 1, '94301': 1, '89436': 1, '15310': 1, '30314': 1, '84120': 1, '13206': 1, '59601': 1, '15103': 2, '30135': 1, '17362': 1, '15035': 1, '12159': 1, '15107': 1, '55054': 1, '44502': 1, '11430': 2, '15037': 1, '08807': 1, '28314': 1, '25301': 1, '44505': 1, '98155': 1, '24540': 1, '17003': 1, '15324': 1, '16314': 1, '32920': 1, '28202': 1, '27546': 1, '51206': 1, '15901': 1, '16040': 1, '23188': 1, '06106': 1, '32801': 1, '11225': 1, '94107': 1, '86314': 1, '15679': 1, '75051': 1, '10801': 1, '15064': 1, '15370': 1, '15330': 1, '59404': 1, '15851': 1, '15026': 1, '18847': 1, '07112': 1, '44512': 1, '15021': 3, '16022': 1, '19406': 1, '43055': 1, '14611': 1, '10710': 1, '15697': 1, '15949': 1, '44404': 1, '15902': 1, '30349': 1, '44004': 1, '15646': 1}
there are  338  different zip codes in this data set

In [6]:
chip3 = pd.read_csv("School Districts.csv", sep="\,")
zipList = []
for i in range(101):#test for the zip code 15203 since it comes up 3 times in 0-15
    x = chip3.iloc[i, 5]
    zipList.append(x)
    
dic2 = dict()
for c in zipList:
    if c not in dic2:
        dic2[c] = 1
    else:
        dic2[c] = dic2[c] + 1
        
column_names=["Zip Code","K-12 Schools"]

df_Schools= pd.DataFrame(list(dic2.items()), columns=column_names)

df_Schools = df_Schools .sort_values("K-12 Schools", ascending=False)

<ipython-input-6-09582cf41f1c>:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  chip3 = pd.read_csv("School Districts.csv", sep="\,")

## Explanation of Data Merging

![alternative text](https://jupyterhub.sci.pitt.edu/user/zic38/files/BigIdeasFinalProject/Final%20Project/Merge%20Explanation%201.png?_xsrf=2%7C1b837f51%7C5da3066ef2109a24e2946de16828dca8%7C1680880464)



![alternative text](https://jupyterhub.sci.pitt.edu/user/zic38/files/BigIdeasFinalProject/Final%20Project/Merge%20Explanation%202.png?_xsrf=2%7C1b837f51%7C5da3066ef2109a24e2946de16828dca8%7C1680880464)

In [7]:
# Data cleaning to prepare for joining data

# dropping NaA values
df_CrimeRates.dropna(subset=['Zip Code'], inplace=True)
df_Schools.dropna(subset=['K-12 Schools'], inplace=True)
df_FastFood.dropna(subset=['Fast Food Resterants'], inplace=True)

df_CrimeRates['Zip Code'] = df_CrimeRates['Zip Code'].astype(int)
joint_df = df_CrimeRates.merge(df_Schools, on='Zip Code', how='right')

joint_df=joint_df.merge(df_FastFood, on='Zip Code', how='left')



joint_df.dropna(subset=['Fast Food Resterants'], inplace=True)
joint_df.dropna(subset=['K-12 Schools'], inplace=True)


joint_df.sort_values("K-12 Schools", ascending=False, inplace=True)
joint_df.head(30)

# Weight scales: Food: 40, Crime:35, School: 25

# Scoring Scales
# schools: max(15) min(1)
# resterants: max(46) min(1)
# Crime Rate: max(34146) min(3970)


joint_df.sort_values("Crime Rates", ascending=False, inplace=True)
joint_df.head(30)

joint_df['Crime Rate Score (weighed 0.4)'] = (1 -joint_df['Crime Rates'] /  34146 )*100*0.4
joint_df["K-12 Schools (weighed 0.35)"] = (joint_df["K-12 Schools"] / 15 )*100 *0.35
joint_df["Fast Food Resterants (weighed 0.25)"] = (joint_df["Fast Food Resterants"] / 46)*100 *0.25

#Joining the dataframes together 

joint_df["Total Score"] = (joint_df['Crime Rate Score (weighed 0.4)'])+(joint_df["K-12 Schools (weighed 0.35)"])+(joint_df["Fast Food Resterants (weighed 0.25)"])

joint_df.sort_values("Total Score", ascending=False, inplace=True)

joint_df.head(30)

,Zip Code,Crime Rates,K-12 Schools,Fast Food Resterants,Crime Rate Score (weighed 0.4),K-12 Schools (weighed 0.35),Fast Food Resterants (weighed 0.25),Total Score
13,15205,3970,3,36.0,35.349382,7.000000,19.565217,61.914599
10,15213,13481,4,38.0,24.207814,9.333333,20.652174,54.193321
6,15216,6126,6,11.0,32.823757,14.000000,5.978261,52.802018
4,15217,11487,6,20.0,26.543665,14.000000,10.869565,51.413231
3,15226,8225,7,7.0,30.364904,16.333333,3.804348,50.502585
16,15222,17142,2,46.0,19.919171,4.666667,25.000000,49.585837
8,15233,5520,5,3.0,33.533650,11.666667,1.630435,46.830751
14,15220,5473,2,15.0,33.588707,4.666667,8.152174,46.407548
9,15201,8705,5,5.0,29.802612,11.666667,2.717391,44.186670
5,15219,21958,6,27.0,14.277514,14.000000,14.673913,42.951427
19,15232,5619,1,12.0,33.417677,2.333333,6.521739,42.272749
7,15208,11349,6,1.0,26.705324,14.000000,0.543478,41.248802
1,15206,24106,10,11.0,11.761260,23.333333,5.978261,41.072855
0,15212,34146,15,9.0,0.000000,35.000000,4.891304,39.891304
11,15207,8592,4,1.0,29.934985,9.333333,0.543478,39.811797
18,15221,8983,1,12.0,29.476952,2.333333,6.521739,38.332024
2,15210,25467,9,11.0,10.166930,21.000000,5.978261,37.145191
21,15224,7786,1,6.0,30.879166,2.333333,3.260870,36.473369
20,15211,7596,1,2.0,31.101740,2.333333,1.086957,34.522029
17,15203,19300,2,19.0,17.391202,4.666667,10.326087,32.383956

In [8]:
# Formating 

joint_df.head(30).round(2)

joint_df.head(30)

,Zip Code,Crime Rates,K-12 Schools,Fast Food Resterants,Crime Rate Score (weighed 0.4),K-12 Schools (weighed 0.35),Fast Food Resterants (weighed 0.25),Total Score
13,15205,3970,3,36.0,35.349382,7.000000,19.565217,61.914599
10,15213,13481,4,38.0,24.207814,9.333333,20.652174,54.193321
6,15216,6126,6,11.0,32.823757,14.000000,5.978261,52.802018
4,15217,11487,6,20.0,26.543665,14.000000,10.869565,51.413231
3,15226,8225,7,7.0,30.364904,16.333333,3.804348,50.502585
16,15222,17142,2,46.0,19.919171,4.666667,25.000000,49.585837
8,15233,5520,5,3.0,33.533650,11.666667,1.630435,46.830751
14,15220,5473,2,15.0,33.588707,4.666667,8.152174,46.407548
9,15201,8705,5,5.0,29.802612,11.666667,2.717391,44.186670
5,15219,21958,6,27.0,14.277514,14.000000,14.673913,42.951427
19,15232,5619,1,12.0,33.417677,2.333333,6.521739,42.272749
7,15208,11349,6,1.0,26.705324,14.000000,0.543478,41.248802
1,15206,24106,10,11.0,11.761260,23.333333,5.978261,41.072855
0,15212,34146,15,9.0,0.000000,35.000000,4.891304,39.891304
11,15207,8592,4,1.0,29.934985,9.333333,0.543478,39.811797
18,15221,8983,1,12.0,29.476952,2.333333,6.521739,38.332024
2,15210,25467,9,11.0,10.166930,21.000000,5.978261,37.145191
21,15224,7786,1,6.0,30.879166,2.333333,3.260870,36.473369
20,15211,7596,1,2.0,31.101740,2.333333,1.086957,34.522029
17,15203,19300,2,19.0,17.391202,4.666667,10.326087,32.383956

In [9]:
joint_df.head(30).round(2)

,Zip Code,Crime Rates,K-12 Schools,Fast Food Resterants,Crime Rate Score (weighed 0.4),K-12 Schools (weighed 0.35),Fast Food Resterants (weighed 0.25),Total Score
13,15205,3970,3,36.0,35.35,7.00,19.57,61.91
10,15213,13481,4,38.0,24.21,9.33,20.65,54.19
6,15216,6126,6,11.0,32.82,14.00,5.98,52.80
4,15217,11487,6,20.0,26.54,14.00,10.87,51.41
3,15226,8225,7,7.0,30.36,16.33,3.80,50.50
16,15222,17142,2,46.0,19.92,4.67,25.00,49.59
8,15233,5520,5,3.0,33.53,11.67,1.63,46.83
14,15220,5473,2,15.0,33.59,4.67,8.15,46.41
9,15201,8705,5,5.0,29.80,11.67,2.72,44.19
5,15219,21958,6,27.0,14.28,14.00,14.67,42.95
19,15232,5619,1,12.0,33.42,2.33,6.52,42.27
7,15208,11349,6,1.0,26.71,14.00,0.54,41.25
1,15206,24106,10,11.0,11.76,23.33,5.98,41.07
0,15212,34146,15,9.0,0.00,35.00,4.89,39.89
11,15207,8592,4,1.0,29.93,9.33,0.54,39.81
18,15221,8983,1,12.0,29.48,2.33,6.52,38.33
2,15210,25467,9,11.0,10.17,21.00,5.98,37.15
21,15224,7786,1,6.0,30.88,2.33,3.26,36.47
20,15211,7596,1,2.0,31.10,2.33,1.09,34.52
17,15203,19300,2,19.0,17.39,4.67,10.33,32.38

In [10]:
joint_df.to_csv('JointDataFrame.csv', index=False)

# Our Best Neighborhood is......Crafton Heights (15205)